### ISSUE TITLE
Add parameter to disable player map tracking

### ISSUE THREAD

**Issue by 7rust** [Jigsor/BMR_Insurgency.Altis#3]
- [ ] Add parameter class
- [ ] Stop executing the tracking script

Just a simple parameter in mission options to disable player map tracking. Adding new parameters will be easier by accepting pull-request https://github.com/Jigsor/BMR_Insurgency.Altis/pull/1

**Comment by Jigsor** [comment]
Change added. Thank you for all the great changes, optimizations and suggestions. I'm still relatively new to github and still learning. Apologies for not pulling your changes that did make it to version 1.46
