### ISSUE TITLE
Parameter to set the amount of civilian units

### ISSUE THREAD

**Issue by 7rust** [Jigsor/BMR_Insurgency.Altis#4]
Would groups allow to increase the amount of civilian units to have a more active environment.

EDIT: Waiting for pull https://github.com/Jigsor/BMR_Insurgency.Altis/pull/1

**Comment by Jigsor** [comment]
There already is parameter for this class CivProbability. Increasing group number or number per group beyond parameter's existing allowance would only result in more civilians spawned in 1 building or bunched up together. A better solution for more dispersion would be to add more marker zones/ call lines in OpenMeCiv.sqf
